---
- name: require implicity localhost
  run_once: True
  when: inventory_hostname == ansible_play_hosts[0]
  assert:
    that:
      - "not groups.all | intersect(['localhost', '127.0.0.1', '::1']) | list"
